apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook-ingestion-service.fullname" . }}
type: Opaque
stringData:
  API_KEY: {{ .Values.apiKey | quote }}
  WEBHOOK_SECRET: {{ .Values.webhookSecret | quote }}

